version: '3'
services:
  # angular:
  #   build:
  #     context: ./
  #     dockerfile: dev.Dockerfile
  #   command: npm run start
  #   volumes:
  #     - ./:/usr/local/app
  #     - /usr/local/app/node_modules
  #   ports:
  #     - '4200:4200'
  #     - '9222:9222'
  #   stdin_open: true
  #   tty: true
  nginx:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DEBUG: 'true'
      ENVIRONMENT: 'development'
      ENVIRONMENT_TAG: 'docker'
      BASE_URL: 'http://localhost/'
      SERVER_NAME: 'localhost'
      CONTACT_URL: 'https://example.com'
      CONTACT_EMAIL: 'user@example.com'
      RAVEN_URL: 'https://sdfdsf9876987sdf987sdfs876sdf9@sentry.example.de/1'
      EMPLOYEE_PICTURES_ENDPOINT: 'https://pictures.example.com/'
      ASSETS_ENDPOINT: 'https://localhost:8081/api/assets'
      ROOMPLANNINGTOOL_URL: 'http://example.com'
      ORGANIZATION_NAME: 'Your very fancy Company'
    ports:
      - 80:80
    volumes:
      - ./nginx.conf /etc/nginx/nginx.conf
      - ./conf.d /etc/nginx/conf.d
    restart: always
    # stdin_open: true
    # tty: true
